[package]
name = "vertigo-demo-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-ws = "0.3"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
thiserror = "2.0"

[dev-dependencies]
awc = "3"
