[package]
name = "vertigo-demo"
version = "0.4.3"
authors = ["Grzegorz Szeliga <szeligagrzegorz@gmail.com>", "Micha≈Ç Pokrywka <wolfmoon@o2.pl>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
log = "0.4.17"
vertigo = { path = "../../crates/vertigo", version = "0.4.3" }
