[package]
name = "vertigo-example-router"
version = "0.9.0"
authors = ["Grzegorz Szeliga <szeligagrzegorz@gmail.com>", "Micha≈Ç Pokrywka <wolfmoon@o2.pl>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vertigo = { path = "../../crates/vertigo", version = "0.9.0" }
