[package]
name = "vertigo-browserdriver"
version = "0.1.0-alpha.3"
authors = ["Grzegorz Szeliga <grzegorz.szeliga@twoupdigital.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Virtual DOM library for Rust - web-browser rendering driver"

[dependencies]
vertigo = { path = "../../crates/vertigo", version="0.1.0-alpha.3" }
wasm-bindgen = {version = "0.2.74", features = ["nightly"]}
wasm-bindgen-futures = "0.4.24"
log = "0.4.14"
